banner:
  charset: UTF-8
eureka:
 instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true  #这里是为了使用ip注册而不是使用docker容器内的主机名
    ip-address: 39.105.110.91
 client:
    serviceUrl:
      defaultZone:  http://39.105.110.91:8760/eureka/
server:
  port: 8763
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: user
  messages:
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.110.91:3306/sensor?useUnicode=true&characterEncoding=utf8
    username: username
    password: password
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM user_list
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  redis:
      database: 0
      host: 39.105.110.91
      port: 6379
      timeout: 6000
      pool:
        max-active: 20 #连接数最大值,使用负数代表不受限制
        max-wait: -1
        max-idle: 10
        min-idle: 5
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    multipart:
      max-file-size: -1 #单个文件大小
      max-request-size: -1 #单词请求文件大小
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.fengsigaoju.health.user.domain.dataobject
logging.config: classpath:log/logging-config.xml
datacenterId: 1
OssClient:
  endPoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIwlvoaIiOgmy7
  accessKeySecret: EidEptlgZG73NTqGGnHqexKQRjkko2
  bucketName: video-spring


