eureka:
  client:
    service-url:
      defaultZone: http://39.105.110.91:8760/eureka/
server:
  port: 8762
spring:
  application:
    name: zuul
  redis:
    database: 0
    host: 39.105.110.91
    port: 6379
    timeout: 6000
    pool:
      max-active: 20 #连接数最大值,使用负数代表不受限制
      max-wait: -1
      max-idle: 10
      min-idle: 5
zuul:
  routes:
    user:
      path: /user/**  #路由到user系统
      serviceId: user
    step:
      path: /step/**  #路由到step系统
      serviceId: step #默认stripprefix是为true也就是step这个不会出现在url里面
    friend:
      path: /friend/**  #路由到friend系统
      servieId: friend
logging.config: classpath:log/logging-config.xml