@startuml
actor 用户
用户->用户信息微服务:用户名+用户名和密码拼接后md5传输
用户信息微服务->mysql:与数据库中用户名和密码md5的结果进行比对
alt 验证通过
用户信息微服务->redis: 生成全局唯一token并存储到session数据库中
用户信息微服务->用户:返回登录成功标识和token
else 验证不通过
用户信息微服务->用户:返回登录失败标识
end
@enduml